name: customer_bengkelly
version: 1.2.6+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  crypto: ^3.0.3
  dio: 5.1.1
  pull_to_refresh: ^2.0.0
  dismissible_page: ^1.0.2
  particles_flutter: ^0.1.4
  launch_review: ^3.0.1
  smartrefresh: ^0.0.2
  http: ^1.2.1
  fine_stepper: ^0.3.0
  webview_flutter: ^3.0.0
  dropdown_button2: ^2.1.2
  package_info: ^2.0.2
  in_app_update: ^4.2.1
  device_info_plus: ^8.0.0
  app_settings: ^5.1.1
  video_player: ^2.9.1
  mobile_scanner: ^3.2.0
  text_scroll: ^0.2.0
  calendar_timeline: ^1.1.2
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.4
  dropdown_search: 5.0.6
  cupertino_stepper: 0.2.1
  carousel_slider: ^4.1.1
  horizontal_week_calendar: ^0.0.10
  go_router: ^13.0.1
  easy_stepper: ^0.8.3
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  curved_navigation_bar: ^1.0.3
  flutter_countdown_timer: ^4.1.0
  flutter:
    sdk: flutter
  firebase_core: ^2.3.0
  firebase_messaging: ^14.9.4
  flutter_onboarding_screen: 2.0.2
  flutter_onboarding_slider: 1.0.9
  flutter_staggered_grid_view: 0.6.2
  curved_labeled_navigation_bar: ^2.0.2
  get: 4.6.5
  get_storage: ^2.1.1
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+4
  intl: 0.18.1
  image: ^4.2.0
  shimmer: ^2.0.0
  shared_preferences: ^2.2.2
  expandable_text: ^2.3.0
  url_launcher: ^6.1.11
  syncfusion_flutter_charts: ^25.1.39
  shimmer_animation: ^2.1.0
  youtube_player_flutter: ^9.0.1
  search_page: ^2.3.0
  file_picker: ^5.2.1
  photo_view: ^0.15.0
  fl_chart: ^0.67.0
  animated_text_kit: ^4.2.2
  android_intent_plus: ^5.0.2
  animations: ^2.0.1
  progress_state_button: ^1.0.4
  quickalert: ^1.1.0
  awesome_dialog: ^3.1.0
  bottom_picker: ^2.6.0
  search_choices: ^2.2.7
  animated_custom_dropdown: ^3.0.0
  bubble_tab_indicator: ^0.1.4
  flutter_local_notifications: ^17.1.2
  horizontal_stepper_flutter: ^1.0.3
  stepper_a: ^1.3.0
  flutter_html_v3: ^3.0.6
  flutter_inappwebview: ^6.0.0
  animated_bottom_navigation_bar: ^1.3.3
  floating_bottom_bar: ^0.0.3
  google_maps_flutter: ^2.6.1
  geolocator: ^7.7.1
  permission_handler: ^10.2.0
  sliding_up_panel: ^2.0.0
  geocoding: ^2.0.0
  table_calendar: ^3.0.6
  stepper_list_view: ^0.0.2
  loading_animation_widget: ^1.2.1
  slide_countdown: ^1.6.1
  pinput: ^4.0.0




dev_dependencies:
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/buku_panduan.pdf
    - assets/buku_panduan_emergency.pdf
    - assets/icons/
    - assets/icons/drop.png
    - assets/icons/logo_nenz.png
    - assets/icons/merci.svg
    - assets/icons/whatsapp.svg
    - assets/icons/whatsapp2.svg
    - assets/icons/youtube.svg
    - assets/images/
    - assets/images/bg.jpeg
    - assets/images/bg.png
    - assets/images/bg2.png
    - assets/images/bghistory.png
    - assets/images/bgnovabar.png
    - assets/images/gamabar20.jpg
    - assets/images/gamabar21.jpg
    - assets/images/gamabar22.jpg
    - assets/images/gamabar23.jpg
    - assets/images/gambar1.jpg
    - assets/images/gambar2.jpg
    - assets/images/gambar3.jpg
    - assets/images/gambar4.jpg
    - assets/images/gambar5.jpg
    - assets/images/gambar6.jpg
    - assets/images/profile.png
    - assets/images/sliderrealbenz1.jpeg
    - assets/images/sliderrealbenz2.jpeg
    - assets/images/sliderrealbenz3.jpeg
    - assets/images/sliderrealbenz4.jpeg
    - assets/images/sliderrealbenz5.jpeg
    - assets/images/sliderrealbenz6.jpeg
    - assets/images/sliderrealbenz7.jpeg
    - assets/images/sliderrealbenz8.jpeg
    - assets/logo/
    - assets/logo/bookingservice.svg
    - assets/logo/logo_autobenz.png
    - assets/logo/logo_autobenz2.png
    - assets/logo/logo_community.jpeg
    - assets/logo/logo_comunity.png
    - assets/produk/
    - assets/produk/acc1.png
    - assets/produk/acc2.png
    - assets/produk/acc3.png
    - assets/produk/acc4.png
    - assets/produk/acc5.png
    - assets/produk/acc6.png
    - assets/produk/acc7.png
    - assets/produk/oli1.jpg
    - assets/produk/oli1.png
    - assets/produk/oli2.jpg
    - assets/produk/oli2.png
    - assets/produk/oli3.png
    - assets/produk/oli4.png
    - assets/produk/oli5.png
    - assets/produk/oli6.jpg
    - assets/produk/oli6.png
    - assets/video/sample_video.mp4
#    - assets/sounds/sounds.mp3

  uses-material-design: true



