/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'customer_bengkelly';
  static const String PLUGIN_VERSION = '1.2.5+1';
  static const String BUKU_PANDUAN = 'assets/buku_panduan.pdf';
  static const String BUKU_PANDUAN_EMERGENCY = 'assets/buku_panduan_emergency.pdf';
  static const String DROP = 'assets/icons/drop.png';
  static const String LOGO_NENZ = 'assets/icons/logo_nenz.png';
  static const String MERCI = 'assets/icons/merci.svg';
  static const String WHATSAPP = 'assets/icons/whatsapp.svg';
  static const String WHATSAPP2 = 'assets/icons/whatsapp2.svg';
  static const String YOUTUBE = 'assets/icons/youtube.svg';
  static const String BG = 'assets/images/bg.jpeg';
  static const String BG1 = 'assets/images/bg.png';
  static const String BG2 = 'assets/images/bg2.png';
  static const String BGHISTORY = 'assets/images/bghistory.png';
  static const String BGNOVABAR = 'assets/images/bgnovabar.png';
  static const String GAMABAR20 = 'assets/images/gamabar20.jpg';
  static const String GAMABAR21 = 'assets/images/gamabar21.jpg';
  static const String GAMABAR22 = 'assets/images/gamabar22.jpg';
  static const String GAMABAR23 = 'assets/images/gamabar23.jpg';
  static const String GAMBAR1 = 'assets/images/gambar1.jpg';
  static const String GAMBAR2 = 'assets/images/gambar2.jpg';
  static const String GAMBAR3 = 'assets/images/gambar3.jpg';
  static const String GAMBAR4 = 'assets/images/gambar4.jpg';
  static const String GAMBAR5 = 'assets/images/gambar5.jpg';
  static const String GAMBAR6 = 'assets/images/gambar6.jpg';
  static const String PROFILE = 'assets/images/profile.png';
  static const String SLIDERREALBENZ1 = 'assets/images/sliderrealbenz1.jpeg';
  static const String SLIDERREALBENZ2 = 'assets/images/sliderrealbenz2.jpeg';
  static const String SLIDERREALBENZ3 = 'assets/images/sliderrealbenz3.jpeg';
  static const String SLIDERREALBENZ4 = 'assets/images/sliderrealbenz4.jpeg';
  static const String SLIDERREALBENZ5 = 'assets/images/sliderrealbenz5.jpeg';
  static const String SLIDERREALBENZ6 = 'assets/images/sliderrealbenz6.jpeg';
  static const String SLIDERREALBENZ7 = 'assets/images/sliderrealbenz7.jpeg';
  static const String SLIDERREALBENZ8 = 'assets/images/sliderrealbenz8.jpeg';
  static const String BOOKINGSERVICE = 'assets/logo/bookingservice.svg';
  static const String LOGO_AUTOBENZ = 'assets/logo/logo_autobenz.png';
  static const String LOGO_AUTOBENZ2 = 'assets/logo/logo_autobenz2.png';
  static const String LOGO_COMMUNITY = 'assets/logo/logo_community.jpeg';
  static const String LOGO_COMUNITY = 'assets/logo/logo_comunity.png';
  static const String ACC1 = 'assets/produk/acc1.png';
  static const String ACC2 = 'assets/produk/acc2.png';
  static const String ACC3 = 'assets/produk/acc3.png';
  static const String ACC4 = 'assets/produk/acc4.png';
  static const String ACC5 = 'assets/produk/acc5.png';
  static const String ACC6 = 'assets/produk/acc6.png';
  static const String ACC7 = 'assets/produk/acc7.png';
  static const String OLI1 = 'assets/produk/oli1.jpg';
  static const String OLI11 = 'assets/produk/oli1.png';
  static const String OLI2 = 'assets/produk/oli2.jpg';
  static const String OLI21 = 'assets/produk/oli2.png';
  static const String OLI3 = 'assets/produk/oli3.png';
  static const String OLI4 = 'assets/produk/oli4.png';
  static const String OLI5 = 'assets/produk/oli5.png';
  static const String OLI6 = 'assets/produk/oli6.jpg';
  static const String OLI61 = 'assets/produk/oli6.png';
  static const String SAMPLE_VIDEO = 'assets/video/sample_video.mp4';
}
