part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const AUTHORIZATION = _Paths.AUTHORIZATION;
  static const SINGIN = _Paths.SINGIN;
  static const SINGUP = _Paths.SINGUP;
  static const SINGUPNEXT = _Paths.SINGUPNEXT;
  static const TEST = _Paths.TEST;
  static const LUPAPASSWORD = _Paths.LUPAPASSWORD;
  static const NEWS = _Paths.NEWS;
  static const HISTORY = _Paths.HISTORY;
  static const PROFILE = _Paths.PROFILE;
  static const CHAT = _Paths.CHAT;
  static const NOTIFIKASI = _Paths.NOTIFIKASI;
  static const BOOKING = _Paths.BOOKING;
  static const EMERGENCY = _Paths.EMERGENCY;
  static const BOOKINGSERVICE = _Paths.BOOKINGSERVICE;
  static const REPAIRMAINTENANCE = _Paths.REPAIRMAINTENANCE;
  static const LOKASIBENGKELLY = _Paths.LOKASIBENGKELLY;
  static const LOKASICHARGER = _Paths.LOKASICHARGER;
  static const EDITPROFILE = _Paths.EDITPROFILE;
  static const PENGATURAN = _Paths.PENGATURAN;
  static const PILIHKENDARAAN = _Paths.PILIHKENDARAAN;
  static const BANTUAN = _Paths.BANTUAN;
  static const DETAILLOKASIBENGKELLY = _Paths.DETAILLOKASIBENGKELLY;
  static const DETAILSPECIAL = _Paths.DETAILSPECIAL;
  static const SELECTBOOKING = _Paths.SELECTBOOKING;
  static const DETAILBOOKING = _Paths.DETAILBOOKING;
  static const DETAILHISTORY = _Paths.DETAILHISTORY;
  static const TAMBAHKENDARAAN = _Paths.TAMBAHKENDARAAN;
  static const SUKSESBOOKING = _Paths.SUKSESBOOKING;
  static const SPLASHSCREEN = _Paths.SPLASHSCREEN;
  static const SPLASHSCREENNO = _Paths.SPLASHSCREENNO;
  static const SEMUALOKASIBENGKELLY = _Paths.SEMUALOKASIBENGKELLY;
  static const LIHATSEMUASPESIALIS = _Paths.LIHATSEMUASPESIALIS;
  static const NEWPASSWORD = _Paths.NEWPASSWORD;
  static const OTP = _Paths.OTP;
  static const LOKASILISTRIK = _Paths.LOKASILISTRIK;
  static const EmergencyBookingView = _Paths.EmergencyBookingView;
  static const UBAHPASSWORD = _Paths.UBAHPASSWORD;
  static const PdfViewScreen = _Paths.PdfViewScreen;
  static const PdfViewScreenEmergency = _Paths.PdfViewScreenEmergency;
  static const PLANNING_SERVICE = _Paths.PLANNING_SERVICE;
  static const DETAILPLANNING = _Paths.DETAILPLANNING;
  static const LihatSemuaToday = _Paths.LihatSemuaToday;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const AUTHORIZATION = '/authorization';
  static const SINGIN = '/singin';
  static const SINGUP = '/singup';
  static const SINGUPNEXT = '/singupnext';
  static const TEST = '/test';
  static const LUPAPASSWORD = '/lupapassword';
  static const NEWS = '/news';
  static const HISTORY = '/history';
  static const PROFILE = '/profile';
  static const CHAT = '/chat';
  static const NOTIFIKASI = '/notifikasi';
  static const BOOKING = '/booking';
  static const EMERGENCY = '/emergency';
  static const BOOKINGSERVICE = '/bookingservice';
  static const REPAIRMAINTENANCE = '/repairmaintenance';
  static const LOKASIBENGKELLY = '/lokasibengkelly';
  static const LOKASICHARGER = '/lokasicharger';
  static const EDITPROFILE = '/editprofile';
  static const PENGATURAN = '/pengaturan';
  static const PILIHKENDARAAN = '/pilihkendaraan';
  static const BANTUAN = '/bantuan';
  static const DETAILLOKASIBENGKELLY = '/detaillokasibengkelly';
  static const DETAILSPECIAL = '/detailspecial';
  static const SELECTBOOKING = '/selectbooking';
  static const DETAILBOOKING = '/detailbooking';
  static const DETAILHISTORY = '/detailhistory';
  static const TAMBAHKENDARAAN = '/tambahkendaraan';
  static const SUKSESBOOKING = '/suksesbooking';
  static const SPLASHSCREEN = '/splashscreen';
  static const SPLASHSCREENNO = '/splashscreenno';
  static const SEMUALOKASIBENGKELLY = '/semualokasibengkelly';
  static const LIHATSEMUASPESIALIS = '/lihatsemuaspesialis';
  static const NEWPASSWORD = '/newpassword';
  static const OTP = '/otp';
  static const LOKASILISTRIK = '/lokasilistrik';
  static const EmergencyBookingView = '/EmergencyBookingView';
  static const UBAHPASSWORD = '/ubahpassword';
  static const PdfViewScreen = '/PdfViewScreen';
  static const PdfViewScreenEmergency = '/PdfViewScreenEmergency';
  static const PLANNING_SERVICE = '/planning-service';
  static const DETAILPLANNING = '/DETAILPLANNING';
  static const LihatSemuaToday = '/LihatSemuaToday';
}
